# Use the official Ubuntu image from the Docker Hub
FROM ubuntu:latest

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Install dependencies
RUN apt-get update && \
    apt-get install -y sudo python3 python3-venv python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a new user called celery with sudo privileges
RUN useradd -m -s /bin/bash celery && \
    echo "celery ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the celery user
USER celery

# Set the working directory
WORKDIR /app

# Create a virtual environment
RUN python3 -m venv venv

# Copy the current directory contents into the container at /app
COPY --chown=celery:celery . /app

# Activate the virtual environment and install the requirements
RUN /bin/bash -c "source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"

# cd to tawjeeh
WORKDIR /app/tawjeeh

# Run the Celery worker
CMD ["/app/venv/bin/celery", "-A", "tawjeeh", "worker", "--loglevel=info"]
