# Use the official Ubuntu image from the Docker Hub
FROM ubuntu:latest

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=tawjeeh.production_settings

# Install dependencies
RUN apt-get update && \
    apt-get install -y sudo python3 python3-venv python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a new user called celery with sudo privileges
RUN useradd -m -s /bin/bash celery && \
    echo "celery ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the celery user
USER celery

# Set the working directory
WORKDIR /app

# Create a virtual environment
RUN python3 -m venv venv

# Copy only the requirements.txt file first to leverage Docker's caching mechanism
COPY --chown=celery:celery requirements.txt /app/

# Install dependencies in the virtual environment
RUN /bin/bash -c "source venv/bin/activate && pip install --upgrade pip && pip install -r /app/requirements.txt"

# Copy the rest of the application code
COPY --chown=celery:celery . /app

# Set the working directory to the tawjeeh directory
WORKDIR /app/tawjeeh

# Run the Celery worker
CMD ["/bin/bash", "-c", "source /app/venv/bin/activate && celery -A tawjeeh.celery beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"]
