# Generated by Django 5.0.6 on 2024-06-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("huggingface_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("huggingface_raw", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "answer_choices",
                    models.CharField(blank=True, max_length=100000, null=True),
                ),
                ("template", models.TextField()),
                (
                    "dataset_subset",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to="prompt.dataset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="tasks",
            field=models.ManyToManyField(related_name="datasets", to="prompt.task"),
        ),
    ]
