# Generated by Django 5.0.6 on 2024-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="text_direction",
            field=models.CharField(
                choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                default="ltr",
                max_length=10,
            ),
        ),
    ]
