# Generated by Django 5.0.6 on 2024-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("RETURNED_FOR_MODIFICATION", "Returned for modification"),
                    ("APPROVED", "Approved"),
                ],
                default="DRAFT",
                max_length=1000,
            ),
        ),
    ]
