# Generated by Django 5.0.6 on 2024-05-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="content",
        ),
        migrations.AddField(
            model_name="prompt",
            name="choices",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="prompt",
            name="name",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prompt",
            name="original_task",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prompt",
            name="template",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
