# Generated by Django 5.0.6 on 2024-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0004_alter_prompt_dataset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="choices",
            new_name="answer_choices",
        ),
    ]
