# Generated by Django 5.0.7 on 2024-09-11 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0005_dataset_default_subset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "dataset_assignments",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "datasets",
                    models.ManyToManyField(
                        related_name="prompting_projects", to="prompt.dataset"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompters",
                    models.ManyToManyField(
                        related_name="prompting_projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
