# Generated by Django 5.0.7 on 2024-09-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0006_promptingproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptingproject",
            name="minimum_prompts_per_prompter",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
