# Generated by Django 5.0.7 on 2024-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0007_promptingproject_minimum_prompts_per_prompter"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptingproject",
            name="secret_key",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
