# Generated by Django 5.0.7 on 2024-10-09 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0009_dataset_subsets_alter_dataset_default_subset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptingproject",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_prompting_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
