# Generated by Django 5.0.7 on 2024-10-14 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0011_prompt_base_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompts",
                to="prompt.task",
            ),
        ),
    ]
