# Generated by Django 5.0.6 on 2024-07-07 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("huggingface_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("huggingface_raw", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "answer_choices",
                    models.CharField(blank=True, max_length=100000, null=True),
                ),
                ("template", models.TextField()),
                (
                    "text_direction",
                    models.CharField(
                        choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                        default="ltr",
                        max_length=10,
                    ),
                ),
                (
                    "dataset_subset",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to="prompt.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptReviewAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                        default="DRAFT",
                        max_length=256,
                    ),
                ),
                (
                    "submitter_comment",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "submitter_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "Approved"),
                            ("RETURNED_FOR_MODIFICATION", "Returned for modification"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "prompt_before_submitter_modifications",
                    models.JSONField(blank=True, null=True),
                ),
                ("taken_on", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_actions",
                        to="prompt.prompt",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="tasks",
            field=models.ManyToManyField(related_name="datasets", to="prompt.task"),
        ),
    ]
