# Generated by Django 5.0.7 on 2024-10-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0010_alter_promptingproject_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="base_prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="child_prompts",
                to="prompt.prompt",
            ),
        ),
    ]
