# Generated by Django 5.0.7 on 2025-05-27 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0014_remove_promptingproject_datasets_dataset_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promptingproject",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="reviewing_prompting_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
