# Generated by Django 5.0.4 on 2025-05-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tawjeehuser",
            name="openrouter_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
