from django.urls import path
from prompt.views import (
    ApplyTemplateView,
    DatasetCreateAPIView,
    DatasetDetailsView,
    DatasetListView,
    DatasetResetCacheView,
    DatasetSearchAPIView,
    DatasetValidationAPIView,
    HFSynchView,
    MultiplePromptsCreateView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectDistributeView,
    ProjectListView,
    ProjectUpdateView,
    PromptCreateView,
    PromptDeleteView,
    PromptListView,
    PromptReviewView,
    PromptUpdateView,
    TaskListView,
    TaskSearchAPIView,
    UserDistributedDatasetsView,
    UserPromptsListView,
)

app_name = "prompt"

urlpatterns = [
    path("task/list", TaskListView.as_view(), name="task_list"),
    path("dataset/list", DatasetListView.as_view(), name="dataset_list"),
    path(
        "dataset/<int:dataset_pk>/prompt/create",
        PromptCreateView.as_view(),
        name="prompt_create",
    ),
    path(
        "dataset/<int:dataset_pk>/prompt/create-multiple",
        MultiplePromptsCreateView.as_view(),
        name="prompt_create_multiple",
    ),
    path(
        "dataset/<int:dataset_pk>/prompt/list",
        PromptListView.as_view(),
        name="prompt_list",
    ),
    path(
        "prompts-list",
        UserPromptsListView.as_view(),
        name="user_prompts_list",
    ),
    path(
        "dataset/<int:dataset_pk>/prompt/<int:pk>/delete",
        PromptDeleteView.as_view(),
        name="prompt_delete",
    ),
    path(
        "dataset/<int:dataset_pk>/prompt/<int:pk>/update",
        PromptUpdateView.as_view(),
        name="prompt_update",
    ),
    path(
        "dataset/<int:dataset_pk>/prompt/<int:prompt_pk>/review",
        PromptReviewView.as_view(),
        name="prompt_review",
    ),
    path(
        "dataset/<int:dataset_pk>/details/",
        DatasetDetailsView.as_view(),
        name="dataset_details",
    ),
    path(
        "dataset/<int:dataset_pk>/reset_cache",
        DatasetResetCacheView.as_view(),
        name="reset_dataset_cache",
    ),
    # path(
    #     "dataset/prompt/merge/",
    #     PromptCreateView.as_view(),
    # ),
    path(
        "dataset/<int:dataset_pk>/prompt/apply-template/",
        ApplyTemplateView.as_view(),
        name="apply_template",
    ),
    path(
        "hf-sync",
        HFSynchView.as_view(),
        name="hf_sync",
    ),
    path(
        "user-distributed-datasets/",
        UserDistributedDatasetsView.as_view(),
        name="my_datasets",
    ),
    # prompting project urls
    path(
        "project/create/",
        ProjectCreateView.as_view(),
        name="project_create",
    ),
    path(
        "project/list/",
        ProjectListView.as_view(),
        name="project_list",
    ),
    path(
        "project/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project_detail",
    ),
    path(
        "project/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "project/<int:pk>/distribute-datasets/",
        ProjectDistributeView.as_view(),
        name="distribute_datasets",
    ),
    path(
        "api/dataset/search/",
        DatasetSearchAPIView.as_view(),
        name="dataset_search_api",
    ),
    path(
        "api/dataset/validate/",
        DatasetValidationAPIView.as_view(),
        name="dataset_validation_api",
    ),
    path(
        "api/dataset/create/",
        DatasetCreateAPIView.as_view(),
        name="dataset_create_api",
    ),
    path(
        "api/task/search/",
        TaskSearchAPIView.as_view(),
        name="task_search_api",
    ),
]
